### ISSUE TITLE
Possible typo in getSwapImageSize()

### ISSUE THREAD

**Issue by eloj** [naivisoftware/vulkansdldemo#4]
The clamp uses `capabilities.maxImageExtent.height` twice, presumably the first occurence should be `capabilities.minImageExtent.height`.

https://github.com/naivisoftware/vulkansdldemo/blob/ac73ab7e8362474a02d68eebbf38271a7c372918/src/main.cpp#L590

**Comment by cklosters** [comment]
Hi, thanks for spotting the typo, fixed here: https://github.com/naivisoftware/vulkansdldemo/commit/56f1af9290c7ae6efa25a81822a08e37a0f5aff9

**Comment by cklosters** [comment]
The final Vulkan implementation of our render engine can be found here, if of interest: https://github.com/napframework/nap/tree/main/modules/naprender/src, including support for MSAA, multiple windows and render targets.
