### ISSUE TITLE
Validation layer name, surface destruction

### ISSUE THREAD

**Issue by kevclarx** [naivisoftware/vulkansdldemo#6]
Thanks for such a clean and minimal sdl vulkan bootstrap, I followed vulkan-tutorial as well and this is nice summary without glfw.

On Vulkan 1.2.162.0 I noticed a couple things I submitted fixes for in https://github.com/naivisoftware/vulkansdldemo/pull/5

- The validation layer name has been changed to VK_LAYER_KHRONOS_validation
- The validation layer complains about instance being destroyed before one of it's children, in this case the presentation_surface

**Comment by cklosters** [comment]
Thanks for the PR, just merged. We recently finished our render Vulkan port (from OpenGL) of our engine. Could be of interest if you're looking for more advanced examples: https://github.com/napframework/nap
